### PR TITLE
WIP: Apple Silicone support

### PR DESCRIPTION
**Pull request by nmunro**
I'm hoping this works, as it appears to build locally but every time I attempt to push it, my network times out, frustratingly.

Hopefully someone can test this and see.

My docker images _should_ be here: https://hub.docker.com/repository/docker/nmunro/rdkit-build-debian/general

### CODE REVIEW

**Comment by tdudgeon** [comment]
Is there a reason why this is done using the Release_2020_03 RDKit release rather than something more recent?
If being based on Release_2020_03 then it really should be done against the branch with that name rather than master.

If I understand correctly then just running build-debian.sh should now build both architectures?

**Comment by nmunro** [comment]
Sorry, that was an oversight on my part, I have updated that. I do have an interesting issues surrounding the deb file that's created as part of the cpack step. It appears in the multi-architecture build the deb artifact is created as one architecture and doesn't have the usual -<arch>.deb suffix. I'm investigating how architecture specific deb files might be created now. 

I'm not overly familiar with cmake/cpack so if you have any idea how to achieve this I'd be grateful for the help, but if not, I'll keep investigating.

**Comment by tdudgeon** [comment]
Sorry, I'm still not clear on the intention here. You updated the tag and rdkit version, but this is still on the master branch.
The master version is used to build the latest rdkit code and build images tagged `latest`. If you want to build images for a specific rdkit release (branch or tag) then that should be done on the corresponding branch. e.g to build from rdkit branch `Release_2023_03` should be done on our `Release_2023_03` branch.
The simplest thing is probably to update to build the latest, or is there a reason why you need to use `Release_2023_03`?

If using latest then `params.sh` should look like this:

```
export DOCKER_TAG=latest
export GIT_REPO=https://github.com/rdkit/rdkit.git
export GIT_BRANCH=master
unset GIT_TAG

export BASE=informaticsmatters
echo "DOCKER_TAG=$DOCKER_TAG GIT_BRANCH=$GIT_BRANCH no tag"
```

**Comment by tdudgeon** [comment]
I'm struggling to get this working, probably partly impacted by my lack of experience with `buildx`. I seem to have a number of problems, mostly around the `TARGETARCH` ARG and the generation of the deb packages (e.g. problems with their names).
Also, I'm not wanting to push the image for the initial build as it is so big, but changing from `--push` to `--load` doesn't seem to work if you are specifying multiple architectures.

On reflection I think it might be better to switch to a multi-stage build, which will make the whole process more efficient (this process was created before multi-stage builds became available).

**Comment by nmunro** [comment]
Yeah, I've been having issues building it, so much so we've set up an aws pipeline to build it with more resources (waiting to see if that completes), yesterday I added a bash function to help name the debian file in an arch specific way (as it seems the build clobbers the deb file leaving one arch without the correct deb) and am now trying to see if I can do the other steps in `build-debian.sh`. 

I still have things to fix, but I agree, a multistage build might be the best way to go, I just finished implementing a multistage build with one of our internal projects and am more than happy to help out, if I can, in implementing this.

**Comment by tdudgeon** [comment]
@nmunro I implemented multi-stage builds and I think that's the way to go.
It's on this branch: https://github.com/InformaticsMatters/docker-rdkit/tree/multi_arch
It uses your buildx approach, but the handling of the deb packages is much simpler now.
Could you take a look and see what you think?

You'll need to change the `BASE` property in `params.sh` and then just run `build-debian.sh`.
The only other file of real interest is `Dockerfile-debian`.
Note: I can't build arm64 versions of the tomcat image right now. I'll need to investigate this.

**Comment by nmunro** [comment]
So, I've tried to build this locally, and I still can't there's something about the build my machine simply can't handle. I'll move this onto my AWS machine and see if I can complete a build there. I am curious though, looking at the code, there's no code for building architecture specific deb files, it might need to be added back in. I'll update you if I have more luck with the other build.

**Comment by tdudgeon** [comment]
The multi-stage build solves the problem of building architecture specific deb files. It pulls them from the appropriate `build` stage image.
You can see the built images on docker hub, tagged `experimental`. e.g. https://hub.docker.com/layers/informaticsmatters/rdkit-python3-debian/experimental/images/sha256-1dbd52924a906c648def0e39126cc7f59dd38ea854dcadefea9e2d38d791226a?context=repo

Could you try one of the arm64 ones as I can't easily test those?

**Comment by nmunro** [comment]
I have just finished running the build, I *think* it worked, here's a link to my dockerhub profile to check: https://hub.docker.com/u/nmunro

**Comment by tdudgeon** [comment]
I've just built the first `latest` and `Release_2023_03` tagged images using the new tooling (from master and Release_2023_03 branches), pushed to the appropriate `informaticsmatters/rdkit-*` tagged images.
If you are able to confirm that these work OK on arm64 platform then I can start to build other recent RDKit releases.
I do not propose to rebuild anything older that 2023_03.
If this all works and you are happy with things then I suggest not to approve this PR in favour of the work on those branches.
Thanks for you help in getting this all sorted.

**Comment by nmunro** [comment]
I've tried using it, however when I start the cartridge container I get this error:

```2023-09-21 09:52:07.343 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-0+deb12u1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2023-09-21 09:52:07.343 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-09-21 09:52:07.343 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-09-21 09:52:07.344 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-09-21 09:52:07.346 UTC [54] LOG:  database system was shut down at 2023-09-21 09:52:07 UTC
2023-09-21 09:52:07.349 UTC [1] LOG:  database system is ready to accept connections
2023-09-21 09:52:18.367 UTC [59] ERROR:  extension "rdkit" is not available
2023-09-21 09:52:18.367 UTC [59] DETAIL:  Could not open extension control file "/usr/share/postgresql/15/extension/rdkit.control": No such file or directory.
2023-09-21 09:52:18.367 UTC [59] HINT:  The extension must first be installed on the system where PostgreSQL is running.
2023-09-21 09:52:18.367 UTC [59] STATEMENT:  CREATE EXTENSION IF NOT EXISTS rdkit```

I've not been able to test it until now, so sorry for the delay.

**Comment by tdudgeon** [comment]
Yes, good spot.
I forgot to include the PgSQL.deb
I'm rebuilding now.Tim

**Comment by nmunro** [comment]
Let me know when it's built and I'll test again :)

**Comment by tdudgeon** [comment]
I've fixed the `latest` and `Release_2023_03` tagged images.
The amd64 ones work OK for me now. Could you check the arm64 ones again?
I'm building other `Release_2023_03_?` ones now. I don't plan to go back further than that unless there's a specific need.

**Comment by tdudgeon** [comment]
The latest and all the Release_2023_03 have now been built.
If everything is working I think we can close this now?

**Comment by nmunro** [comment]
Yeah, I've just tested it and it seems to work! Thanks for everything you did on this!

**Comment by tdudgeon** [comment]
Closing as the multi-stage build approach has superseded this.

**Pull request closed without merging**
